### ISSUE TITLE
hydromt/raster.py sets np.nan as nodata value, which causes an error when only numerical nodata values are supported

### ISSUE THREAD

**Issue by pauwiersma** [Deltares/hydromt_wflow#153]
I get the following error when trying to setup staticmaps for my study area with hydromt=0.6.0 and hydromt_wflow=0.2.1: 

```
(hydromt_wflow) tesla-k20c@teslak20c:/mnt/scratch_pwiersma/PauWiersma/Data/HydroMT$ hydromt build -i wflow_thur.ini -d data_sources_thur_newsoil                                             s.yml wflow . "{'geom':'Thur_Jonschwil.geojson'}" -vv -r 0.00833333333333334883
2023-02-17 18:33:01,972 - build - log - DEBUG - Writing log messages to new file /mnt/scratch_pwiersma/PauWiersma/Data/HydroMT/hydromt_wflow.log                                             .
2023-02-17 18:33:01,972 - build - log - INFO - HydroMT version: 0.6.0
2023-02-17 18:33:01,972 - build - main - INFO - Building instance of wflow model at /mnt/scratch_pwiersma/PauWiersma/Data/HydroMT.
2023-02-17 18:33:01,972 - build - main - INFO - User settings:
2023-02-17 18:33:02,046 - build - data_catalog - INFO - Parsing data catalog from data_sources_thur_newsoils.yml
2023-02-17 18:33:02,159 - build - model_api - WARNING - Model dir already exists and files might be overwritten: /mnt/scratch_pwiersma/PauWiersm                                             a/Data/HydroMT/staticgeoms.
2023-02-17 18:33:02,159 - build - model_api - WARNING - Model dir already exists and files might be overwritten: /mnt/scratch_pwiersma/PauWiersm                                             a/Data/HydroMT/instate.
2023-02-17 18:33:02,159 - build - model_api - WARNING - Model dir already exists and files might be overwritten: /mnt/scratch_pwiersma/PauWiersm                                             a/Data/HydroMT/run_default.
2023-02-17 18:33:02,159 - build - model_api - INFO - Initializing wflow model from hydromt_wflow (v0.2.1).
2023-02-17 18:33:02,160 - build - model_api - DEBUG - Setting model config options.
2023-02-17 18:33:02,162 - build - model_api - DEBUG - Default config read from /home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-pa                                             ckages/hydromt_wflow/data/wflow/wflow_sbm.toml
2023-02-17 18:33:02,163 - build - model_api - INFO - setup_basemaps.region: {'geom': 'Thur_Jonschwil.geojson'}
2023-02-17 18:33:02,163 - build - model_api - INFO - setup_basemaps.res: 0.008333333333333349
2023-02-17 18:33:02,163 - build - model_api - INFO - setup_basemaps.hydrography_fn: merit_hydro
2023-02-17 18:33:02,163 - build - model_api - INFO - setup_basemaps.basin_index_fn: merit_hydro_index
2023-02-17 18:33:02,163 - build - model_api - INFO - setup_basemaps.upscale_method: ihu
2023-02-17 18:33:02,163 - build - wflow - INFO - Preparing base hydrography basemaps.
2023-02-17 18:33:02,163 - build - data_catalog - INFO - DataCatalog: Getting merit_hydro RasterDataset raster data from /mnt/scratch_pwiersma/Pa                                             uWiersma/Data/HydroMT/static_data/base/hydro_merit/*vrt
2023-02-17 18:33:02,662 - build - basin_mask - DEBUG - Parsed region (kind=geom): {'geom': 'GeoDataFrame [ 8.96666667 47.145       9.365      47                                             .41666667] (crs = EPSG:4326)'}
2023-02-17 18:33:02,714 - build - wflow - DEBUG - Adding basins vector to staticgeoms.
2023-02-17 18:33:02,715 - build - basemaps - DEBUG - (Sub)basin at original resolution has 84337 cells.
2023-02-17 18:33:03,970 - build - basemaps - INFO - Upscale flow direction data: 10x, ihu method.
2023-02-17 18:33:20,699 - build - basemaps - DEBUG - This is a patch for basins which are clipped based on bbox or wrong geom
2023-02-17 18:33:21,341 - build - main - ERROR - cannot convert float NaN to integer
Traceback (most recent call last):
  File "/home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-packages/hydromt/cli/main.py", line 185, in build
    mod.build(region, res, opt=opt)
  File "/home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-packages/hydromt/models/model_api.py", line 220, in build
    self._run_log_method(method, **opt[method])
  File "/home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-packages/hydromt/models/model_api.py", line 153, in _run_log_method
    return func(*args, **kwargs)
  File "/home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-packages/hydromt_wflow/wflow.py", line 200, in setup_basemaps
    ds_base, _ = workflows.hydrography(
  File "/home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-packages/hydromt_wflow/workflows/basemaps.py", line 152, in hydrography
    ds["mask"]
  File "/home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-packages/hydromt/raster.py", line 1516, in reproject_like
    da = self.clip_bbox(dst_bbox, buffer=2).raster.reproject(
  File "/home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-packages/hydromt/raster.py", line 1470, in reproject
    da_reproj = _reproj(self._obj, **reproj_kwargs)
  File "/home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-packages/hydromt/raster.py", line 1447, in _reproj
    return da.raster._reproject(**kwargs)
  File "/home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-packages/hydromt/raster.py", line 1357, in _reproject
    da_reproject = full(
  File "/home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-packages/hydromt/raster.py", line 109, in full
    da.raster.set_nodata(nodata)
  File "/home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-packages/hydromt/raster.py", line 1314, in set_nodata
    self._obj.rio.write_nodata(nodata, inplace=True)
  File "/home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-packages/rioxarray/raster_array.py", line 327, in write_nodata
    input_nodata = _ensure_nodata_dtype(input_nodata, self._obj.dtype)
  File "/home/tesla-k20c/.conda/envs/hydromt_wflow/lib/python3.10/site-packages/rioxarray/raster_writer.py", line 130, in _ensure_nodata_dtype
    nodata = numpy.dtype(new_dtype).type(original_nodata)
ValueError: cannot convert float NaN to integer
```

This happens during the upscaling of elvtn and flwdir. The data originally doesn't have a nodata value, so it's set to np.nan (line [1649](https://github.com/Deltares/hydromt/blob/e168caee330d4370d1bcff2c68d5ce789229c727/hydromt/raster.py#L1649) of raster.py). But then in line [1479](https://github.com/Deltares/hydromt/blob/e168caee330d4370d1bcff2c68d5ce789229c727/hydromt/raster.py#L1479) it says only numerical nodata values are supported and three lines later ([1482](https://github.com/Deltares/hydromt/blob/e168caee330d4370d1bcff2c68d5ce789229c727/hydromt/raster.py#L1482)) the error occurs. 

Is this a bug? And if not, how can I work around this error and make sure to pass a numerical nodata value? Thanks!

**Comment by hboisgon** [comment]
To build a model with hydromt we recommend using the 'basin' or 'subbasin' keywords because wflow is a basin wide hydrology model. ONly if you are 100% sure your geometry file fits perfectly the catchment boundary, you should basin or subbasin followed then by either point coordinates/bounding box/geometry file etc.
See https://deltares.github.io/hydromt_wflow/latest/user_guide/wflow_build.html and https://deltares.github.io/hydromt/latest/user_guide/model_region.html

Does this solves your issue?

**Comment by pauwiersma** [comment]
Thanks a lot for your answer. It has solved my issue partly, there were several other steps I had to take before getting HydroMT to work. 

I tried using a bounding box because it had worked for me in a previous HydroMT-wflow version, and now it also worked for the Piave basin example, but not for the Thur basin I'm trying to set up. I'm guessing it's because the Thur doesn't have a pit in the bounding box because it doesn't drain in the sea, so it doesn't match t[his if-statement](https://github.com/Deltares/hydromt_wflow/blob/8ae03b40a22382b3c9f8512174b3c0d74c6c3f53/hydromt_wflow/workflows/basemaps.py#L141) which is at the source of the error. 

Once I defined my subbasin at [9.0775,47.4137] I got a different error:

```
2023-02-23 16:53:28,395 - build - basin_mask - INFO - subbasin bbox: [9.0771, 47.4129, 9.0771, 47.4129]
2023-02-23 16:53:28,921 - build - main - ERROR - 'data' should be array of geometry objects. Use from_shapely, from_wkb, from_wkt functions to construct a GeometryArray.
```
which I managed to solve by adding 'strord':4. I'm guessing the default stream order is higher and that this is why the river at my xy location was not picked up, but from the documentation this is not very clear. I just tried my luck with something I saw in the examples. 

Slightly unrelated, but finally I also had some trouble with the soilgrids soilthickness map. I copy-pasted the soilthickness map from soilgrids v2017 and interpolated it to the v2020 grid, but I'm guessing this is not the ideal way to obtain it. This was also not clear from the documentation. 

While I found a workaround, the fact that nans are written to a dataset that are subsequently not supported by the same code might cause problems further on. I also believe some more documentation on 'strorder' and soilthickness could help future users. Hope this is not too much for one issue, let me know if I should create a separate issue for any of this and thanks again for your help.

**Comment by hboisgon** [comment]
We can indeed explain more about subbasin in the documentation that you need to add some snapping option like streamorder or upstream area. I'll open an issue in the core for it (where the region documentation is located).

For soilthickness this is a different issue. HydroMT considers that the soildatabase comes from one data source only not two. So if you prepare a soilthickness map that is not from the same version, you should make sure that the grid definition is exactly the same as the rest of the dataset (from v2017 to v2020) and for example QGIS does not do this properly. Doesn't soilgrids v2020 has its own soilthickness map? If not and turns out that this situation happens more often, we could split the data source for setup_soilmaps to use one data source for soil properties and a potential separate one for soilthickness. Then you would not have to worry about exact interpolation of your soilthickness map.

For your NaN issue, if your dataset does not have an original NaN value, you can specify one in the data catalog directly (should respect your dataset data type)

**Comment by pauwiersma** [comment]
I used xarray to interpolate the 2017 soilthickness to the 2020 grid and it worked fine. I haven't been able to find a soilthickness map from the 2020 release, so yeah splitting the data source seems a good solution. 

I haven't tried specifying another nodata value in the data catalog. That might work but it that case it should perhaps be made  clearer that np.nan as a nodata value is not always supported (e.g. by the set_nodata function in [hydromt/raster.py ](https://github.com/Deltares/hydromt/blob/e168caee330d4370d1bcff2c68d5ce789229c727/hydromt/raster.py#L1465)).

**Comment by hboisgon** [comment]
I opened three new issues in hydromt and hydromt_wflow related to the different topics in our discussion. If you agree and I indeed got everything then I will close this discussion and we will continue with the separate new issues :)
Thanks for flagging them out!

**Comment by pauwiersma** [comment]
Yes, that's perfect. Thanks to you as well!
